/*
IIIIIII??I??????????????????????????????????????????????????????????????????????
???II???????????????????????????????????????????????????????????????????????????
????????????????????????????????+++++????+???+??????????????????????????????????
??????????????????????????+?++?$NNMNNMMMMNDO$?=+??++++++++++????????????????????
?????????????????????+?+?=$DNDDDNNDDDDDDDD88DDDDND+=+++++++++++++++?????????????
??????????+++?+++++++++?ODNDDDOOD8DO88O8OOOZZZ8OOODONI=+++++++++++++++++++++++++
?????+?++++++++++++++7DDND88OOO8OOOOO$7Z$$ZZZZZOZZO788OZ++++++++++++++++++++++++
++++++++++++++++++++$DDNDDO88O8OOO$$7777$777I7$7$Z$I$OZOO?+=++++++++++++++++++++
++++++++++++++++++~DNDDD8D8OZO$7I$II?++++?+++++??I7II7Z77O7===++++++++++++++++++
++++++++++++++++==MNND8ZZOZZZII??+++=====~~~~~~~~=++?77$7$8N+=++==========++++++
+++++++++++++====ONND8OZ7$7I7?+??+++=====~~~~~~~~~~=++I7Z7ODN===================
++++++++=====+=+7NNND8O$$I7I??++++=======~~~~~~~~~=~~=+?$I7OD~==================
+++==========+=:MNNNN8Z77I77???+++==~=~~~~~~::::~~~~===?I7Z88N~=================
==============~ONMNND8$Z?$77I??++=+====~~~~:::::~:~~~~==II$8DN==================
==============~MMNNND8$77$$7I?++++==~===~~~~~~~::::~~===+I88DN+~================
=============~~MMNNND8Z7$Z$77??+++==~~~~~~~~~~~:~::~~~==+I$DNM===~~=============
==============+MMNNNDOZ$ZZ$$I+?++===~~~~~~~~~:::::::~~=~=?Z8DM:~~~~~~~~~~~~~~~~~
========~~~~~=~MMMNNNOOOZZ$$$II??++=~:~~~:===:::::~~~===??ODNM:~~~~~~~~~~~~~~~~~
===~~~~~~~~~~~~NMMNNNO8OZZZ$Z7$7$I?I?=~+~~++=+=+=~~=+===+?ZNNO~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~:MMNNND$Z$ZO77I?+=~:::D$=~~+NDI=~::::?ND?+78NN~~:~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~8DNNNDNDMDZZZZ$I?7???=+MODN$77I+~~=~~~=~N8DNO~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~:OZ88OO$$M$888DZIZ7IDOZ7MMN=?78ZN8$D7:===M=$O7~~~~:~~~~~~~~~~~~~~
~~~~~~~~~~~~~~::O$ZZOZZZM7$7I??++=+~?$ON~7?~??+==::~====M~~O+::~:::::::::::::~~~
~~~~~~~~::::::::ZZZOZZZ$M7I?I???++?+?8MI~,M+=I??+=~~~=~~D~~I=:::::::::::::::::::
~~~:::::::::::::IZZZZZZ$ZI???++~~~=+$M7+::~M===++=~~~=~:==~+::::::::::::::::::::
::::::::::::::::,ZOZZZ$ZZ7D?+=+=~~IMN$7+~,~~M~?+==~:~~:D===:::::::::::::::::::::
:::::::::::::::::ZZOZZZZZZ$$7O8DD8Z7?ZZ+=:~~:IO8I??IZO:==~+:::::::::::::::::::::
::::::::::::::::::$$ZZZZZZ7?+===~7$ZNMN$I=$N7~+==~=~~=~==~~:::::::::::::::::::::
:::::::::::::::::,$ZZZZZZZZZ7I+???$ZZ$ZO$=::=~::??=======~::::::::::::::::::::::
:::::::::::::::::,:O$ZZZ$ZZO$$7777I?+==~~~~~::~~=+II++==~~,,,,,,,,,:::::::,,,:::
::::::::::::::::,,:=ZZZZZZZ7?$77$7??++=~~~:~~~~==+++=~~==~:,,,,,,,,,,,,,,,,,,:::
:::::,::::,,,,,,:,:,ZZZZZZZ7+7$OZZ7II7I?========?===~~~=,,,:,,,,,,,,,,,,,,,,,,,,
::::::,,,,,,,,,,,,:.O$ZZZZZ7I+7OZO8N8NNNNNNNZ=:=+======+,,,,,,,,,,,,,,,,,,,,,,,,
:::,,,,,,,,,,,,,,,,,?$$ZZZZ$7+?$$77?I7I+==:==~:~======+=,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,.ZZZZZZZZI??777I7?+?++~~~~~~==++++?,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,.$ZZ$ZOZOOO7+77????+++==~~~=~==?+++,,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,.,DNM?ZZZOOOOO7?$?++==~~~:::~~~=+?++,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,NNNMD+ZZOOOO8O$I7I?++=+=~~~~~=I?I=:,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,:.,,..NMMNNMM=8ZZO8O8OO$$ZII?????++I?II=~.,..........................
,,,,,,,,,,..?MMMDNNNMMMMM~+8OZOOOOOOZZZZOOOZZI7I+I~,............................
,,,...,,.~MNMMMMNNMMMMMMMM~+~$8ZOZZZOOOOZ7I777II+~DDDDDNN?........,.............
,,,,.,.:NDNNMMMMMMMMMMMMMNM+==~+OZZ$7$$Z$$7I?I?=~.8D8DDDDDDN8...................
.,...MDDDDDNNMMMMMMMMMMMMMMMD+==~=+7$ZZ$7?~++==...N8DDDDDDDDDDDDO...............
OMDDDDDDDDDDNNNNMMNMMMMMMMMMNZ~=~~:,.:O77?===.....M888DDDDDDD888DDDDM~..........
DDDDDDDDDDDDDNNNNMNNNNNMNNMNNDZ:~:,....$87O8$,....M8D8888DDDDD888888DDDDM=......
DDDDDDDDDDDDDDDNNMNNNNNNNNNNNNN+:::,.~8OZI7ZZ+$...ND8888D8DDDDDD888D8888D8N8..,.
DDDDDDDDDDDDDDDDNMNNNNNNNNNNNDND,,,.DND87Z7O$88$..ODD8888D8DDDDD888DDDD8DD88DDD.
DDDDDDDDDDDDDDDDNMNNNNNNNNNNNDDDD+=8DD8$87ZZ?D?7?.$D8888DDDD8DDDDDDDD8D88888DDDD
DDDDDDDDDDDDDDDDNMNNNNNNNNNNNDDDDN.,$+ZDDDO=$,?II~+D8DD8DDDDDDDDDD8DDDD888888DDD
DDDDDDDDDDDDDDDDNMNNNNNNNNDDDDDDD8M.,?==D8D8Z.,...+DDDDD88DDDD8DDDDDDD8888888888
DDDDDDDDDDDDDDDDMMNNNDNDDDDDDDDDDDDM.+7=$ODZI~....I+DDDDDD88DDD8D8DDDDD888888888
DDDDDDDDDDDDDDDDMMMNNDDDNDDDDDDDDD88M,7$D8$OZO..,.$?NDDDDDDD8DD88D8DD88888888888
DDDDDDDDDDDDDDDDDMMMMMMMMMDDDDDDD88DD:~D$DDD?ZO...I?NDDDDDDDD88DDDDDD88888D8D888
DDDDDDDDDDDDDDDDDDDNNMMMMDDDDDDDDDDDDDOID$D8O$O8,:I?NDDDDDDDDDDDDDDDD88888888888
NDDDDDDDDDDDDDDDDDDDDDNMDDDDDDDDDDDDDDNDODOOZOO78:7?8DDDDDDDDDDDDDDD8D8888888888
NNDDDDDDDDDDDDDDDDDDDDMDDDDDDDDDDDDDDDDDNOD8ZZZZZ887ZDDDDDDDDDDDDDDDD8D88D888888
MNDDDDDDDDDDDDDDDDDDDMDDDDDDDDDDDDDDDDDDDNI7Z$?O?O8O$DDDDDDDDDDDDDDDDDDDDD888888
MMNNDDDDDDDDDDDDDDDDMMDDDDDDDDDDDDDDDDDDDD8O77O+OZDD7DDDDDDDDDDDDDDD88DD88888888
DMMNDDDDDDDDDDDDDDDDNMMDDDDDDDDDDDDDDDDDDDDZZZ=$77DD7DDDDDDDDDDDDDDD88DDDD888888
DDMMNDDDDDDDDDDDDDDDDMMMDDDDDDDDDDDDDDDDDDD88=ZZIOZD$DDDDDDDDDDDDDDDDDDDDD8D8888
NDMMNNDDDDDDDDDDDDDDDNMMNDDDDDDDDDDDDDDDDDDNOOZZO+N87DDDDDDDDDDDDDDDDDDDDDDD8888
MNMMMNNDDDDDDDDDDDDDDDNMMMDDDDDDDDDDDDDDDDDND$OO7ODM+DDDDDDDDDDDDDDDDDDDDDD88888
NMMMMNNNDDDDDDDDDDDDDDDNMMMDDDDDDDDDDDDDDDD8DNZ7OZNM8DDDDDDDDDDDDDDDDDDDDDDD88DD
NNMMMMNNDDDDDDDDDDDDDDDDNMMNDDDDDDDDDDDDDDDDN8D?ZZMMNDDDDDDDDDDDDDDDDDDDDDDD8888
*/

//Put this file in your project directory and add #include "bugproof_header.h"
//into your source code file to make your program bugproof.
//Hail our senior!!!
